# -*- coding: utf-8 -*-
"""expertshub_spacy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/169phyTTtJNjfD852MH33PLgXJCRrFy29
"""

'''pip install datefinder
python -m spacy download en_core_web_sm
pip install dateparser'''

import spacy
import datetime
import dateparser

word_list=[]

nlp=spacy.load('en_core_web_sm')
query = 'Remind me to do homework on 31th December at 1 p.m. '            
for word in query.split(' '):
  wk = word
  word = word.replace("th","")
  word = word.replace("rd","")
  word = word.replace("st","")
  word = word.replace("nd","")
  try:
    temp = int(word)
    if len(word==1):
      word = "0"+word
      query = query.replace(wk,word)
  except:
    pass
doc=nlp(query)
adjs=[]
for token in doc:
  if token.pos_=="ADJ":
    adjs.append(token.text)
for token in doc:
  word_list.append(token.text)

'''
Checking if Remind phrase is present or not
'''

if "Reminder" in word_list or "Remind" in word_list or "remind" in word_list or "reminder" in word_list:
  '''
  Verb list
  Noun list
  Date list
  Time list
  '''
  ################################################################################
  def verb(x):
    verb_list=[]
    for token in x:
      if token.pos_=='VERB':
        verb_list.append(token.text)
    return verb_list
  ################################################################################
  def noun(x):
    noun_list=[]
    for token in x:
      if token.pos_=='NOUN':
        noun_list.append(token.text)
    return noun_list
   ################################################################################
  def date(x):
    date_list=[]
    for token in x.ents:
      if token.label_=='DATE':
        date_list.append(token.text)
    return date_list
  ################################################################################
  def time(x):
    time_list=[]
    for token in x.ents:
      if token.label_=='TIME':
        time_list.append(token.text)
    return time_list
  ################################################################################
  Noun=noun(doc)
  Verb=verb(doc)
  ################################################################################
  for i in Noun:
    if 'p.m.' in Noun:
      Noun.remove('p.m.')
    if 'a.m.' in Noun:
      Noun.remove('a.m.')
    if 'reminder' in Noun:
      Noun.remove('reminder')
    if 'Reminder' in Noun:
      Noun.remove('Reminder')
   ################################################################################
    
    
    
    '''
    Getting date and time
    '''
    time_set=dateparser.parse(time(doc)[0],settings={'TIMEZONE': 'GMT+5:30'})


    hour,mins,secs=time_set.hour,time_set.minute,time_set.second

    if not date(doc):
      default_date=datetime.datetime.now()
      day,month,year=default_date.day,default_date.month,default_date.year
    else:
      date_set=dateparser.parse(date(doc)[0],settings={'PREFER_DATES_FROM': 'future'})
      day,month,year=date_set.day,date_set.month,date_set.year

#     print(day,month,year)
#     print(hour,mins,secs)
    
    '''
    Displaying task
    '''


    task=(Verb[1]+' '+Noun[0])
    print(task ,'at',hour,':',mins,':',secs,'on',day,'-',month,'-',year)

  ################################################################################
else:
  print('I won\'t Remind you anything')
